name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite rodar o processo manualmente no GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configurar Flutter (Usado pelo Flet)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Flet
        run: |
          pip install flet
          pip install -r requirements.txt

      - name: Compilar o APK
        run: flet build apk

      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: MeuApp-APK
          path: build/apk/**/*.apk
